### ISSUE TITLE
Ngx-php is NOT using OPcache

### ISSUE THREAD

**Issue by joanhey** [soulteary/ngx-php-micro-blog#2]
Both need to use OPcache to compare it.

Apache-buster is using OPcache but ngx-php NO.
OPcache have a really big impact in PHP performance.

Apache-buster:
![image](https://user-images.githubusercontent.com/249085/194198552-e9632b4c-5285-48de-9d10-6fb28f7faad6.png)

Ngx-php without Zend OPcache
![image](https://user-images.githubusercontent.com/249085/194198692-5a234726-94c6-406a-b847-bb5c8f835ab8.png)

**Comment by soulteary** [comment]
Yes, as mentioned in the article (chinese), using **unoptimized ngx-php and the official PHP docker image** for performance comparison, it seems that the results are more obvious.

**Comment by joanhey** [comment]
It's a PHP optimisation not a ngx-php optimisation.

Later we will show that if we use the php in another way in ngx-php, it's the same if OPcache is used or not.
